# Generated by Django 3.1 on 2020-08-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('real_name', models.CharField(max_length=30)),
                ('origin', models.TextField(max_length=255)),
                ('gener', models.CharField(choices=[('h', 'Heroes'), ('m', 'Villians')], max_length=2)),
            ],
        ),
    ]
