# Generated by Django 3.1 on 2020-08-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gener',
            field=models.CharField(choices=[('h', 'Heroes'), ('v', 'Villians')], max_length=2),
        ),
    ]
