name: Integración continua

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  tests:
    name: Pruebas y Calidad del Código
    runs-on: ubuntu-18.04
    container:
      image: python:3.7
      env:
        DJANGO_SETTINGS_MODULE: config.settings.ci
    steps:
      - uses: actions/checkout@v2
      
      - name: Instalandon dependencias
        run: pip install -r requirements/ci.txt
      
      - name: Corriendo pruebas y obteniendo el coverage
        run: make coverage 

      - name: Pasando el linter a mi código
        run: make lint
